Checking for already offered or already chosen driver
CMPUT301F16T01/Carrier pull request #132
Opened 2016-11-15 19:20 UTC by Hreherch

I haven't tested yet, but I think this is a fix. (Squash if you test and agree)

2016-11-16 03:01 UTC, Hreherch commented
Still need to check if the checks are working for offering, but I'm suddenly a lot more relieved.

2016-11-16 06:04 UTC, Hreherch commented
Ready for merge/review
Solves: #148, #134, #131, #151 

@sehoven, @MandyMeindersma, @kieter, @MichaelParadis

2016-11-16 08:41 UTC, Hreherch commented
Pull request now also implements code for #127 and #152 (swipe refresh, I think there's two issues).

2016-11-17 00:29 UTC, MandyMeindersma requested changes
Once you look at all these comments could you see what was up with that weird crashing error. 

Other than that you did a wonerful amazing job and I am so proud of you

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/StatusTests.java
> +import comcmput301f16t01.github.carrier.Users.User;
yay beautiful imports

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +import android.util.Log;
Do we still need logs now? its just debugging?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +    public void logout() {
update the issue <3

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +             * user: iamlukeyb
is this in the wiki?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                    if(!ConnectionChecker.isConnected(getContext())) {
cool. Good offline stuff

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                        public void update() {
What is finish? and why is it 2? can we comment here?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                    //mSectionsPagerAdapter.notifyDataSetChanged();
delete this line now?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                    //bundle.putString("request", new Gson().toJson(requestList.get(position)));
delete this now?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +
I AM SARAH DO NOT LEAVE BLANK LINES

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                    //bundle.putString("request", new Gson().toJson(requestList.get(position)));
PLEASE DELETE THIS LINE

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/DriverViewRequestActivity.java
> +import com.google.gson.Gson;
dem imports ;)

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/DriverViewRequestActivity.java
> +        //request = new Gson().fromJson(bundle.getString("request"), Request.class);
delete this now

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/DriverViewRequestActivity.java
> +            view.setEnabled(false); // Make the button un-clickable after offering.
great comments

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +    public RequestList getOffersInstance() {
loving the comments

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +        //request = new Gson().fromJson( bundle.getString("request"), Request.class );
delete this line?

2016-11-17 00:29 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchResultsActivity.java
> +                bundle.putInt( "position", -1 );
? what does this do? add a comment?

2016-11-20 00:56 UTC, Hreherch commented
@MandyMeindersma I'm not going to fix the space because that's a simple refactor right click action and we can do that at the end and I don't want merge conflicts. But I think I'm done, test it out!

2016-11-21 06:23 UTC, MandyMeindersma approved these changes

2016-11-21 06:23 UTC, merged