Merge search-by-location into Master
CMPUT301F16T01/Carrier pull request #158
Opened 2016-11-17 18:13 UTC by sehoven

Wrote searching tests and search by location functionality

2016-11-20 01:21 UTC, Hreherch requested changes
I'm not sure if I can confirm/deny that the "null location" issue is correct, do you happen to have a test for it that I missed? (Not a necessary component to complete for approval) 

Otherwise doing great! Just some minor things to potentially change.

2016-11-20 01:21 UTC, Hreherch commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/SearchingTests.java
>      protected void tearDown() throws Exception {
Is it working as expected?
Can you add a comment as to what your tearDown() method does?

2016-11-20 01:21 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> +     *       }
Can we keep these somewhere else, like on the Wiki?

2016-11-20 01:21 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        // TODO check how these are sorted, we want to sort them by those closest to those furthest away
Did you complete this TODO while working on this branch? (I remember you mentioning it)

2016-11-20 01:21 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/UserController.java
> +            return "That doesn't look like a valid phone number!";
💁 My bad, thank you for catching this!

2016-11-20 01:21 UTC, Hreherch commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/SearchingTests.java
>      public void testDriverSearchByLocation() {
In comments could I have what you are testing, and if you test for any exceptional cases? 
Also maybe include reference to which use case this tests, if applicable.

2016-11-21 03:03 UTC, sehoven commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/SearchingTests.java
>      protected void tearDown() throws Exception {
Created an issue to implement the fix from the singleton-refactor branch once both are merged to master.

2016-11-21 03:19 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> +     *       }
Moved to Google Docs.

2016-11-21 03:50 UTC, sehoven commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/SearchingTests.java
>      public void testDriverSearchByLocation() {
Added use case references.

2016-11-21 03:50 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        // TODO check how these are sorted, we want to sort them by those closest to those furthest away
Thank you. I removed this TODO. This is done.

2016-11-21 04:40 UTC, sehoven commented
The null location fix is in SetLocationsActivity.java in the getCurrentLocation() method. I check if lastLocation is null (which only happens if there was a problem retrieving the current location). If it is null, it defaults to (0, 0) (which is somewhere in the middle of the ocean).

2016-11-21 10:17 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> +>>>>>>> 92fda80c294f949b664f49d206e3dedeea1f17a7
Git decided to be awkward.

2016-11-21 10:35 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> +>>>>>>> 92fda80c294f949b664f49d206e3dedeea1f17a7
You don't have to fix this, it's in #167, I think. 
I'll approve this branch when you merge that with it's changes?

2016-11-22 05:25 UTC, Hreherch commented
The only minor issue I can find is that I can offer twice on the same request if I haven't gone all the way back to the search buttons, this is more of an enhancement at this point. 
Also "Search Results s" is one of the titles. But that's more of a quality issue :P

2016-11-22 05:25 UTC, Hreherch approved these changes

2016-11-22 05:25 UTC, merged