Search Price Filtering Feature
CMPUT301F16T01/Carrier pull request #166
Opened 2016-11-20 19:57 UTC by Hreherch

You can now filter by price when searching by location or keyword.

2016-11-21 07:49 UTC, sehoven requested changes
I think because you pulled a branch or two there's A LOT going on here so I focussed my attention on the filtering part. I did some skimming over the parts that didn't seem relevant so if someone else had time to also skim that would probably be beneficial.

2016-11-21 07:49 UTC, sehoven commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/ElasticUserControllerTest.java
>   */
This auto-generated Javadoc should be removed

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +
This is so cool I love this.

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/Request.java
> +                "Price: " + getFare() + "\n" +
Do FareCalculator fc = new FareCalculator(); fc.toString(getFare()); to get a properly formatted fare (right now it is the fare * 100)

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/Request.java
> +                "Price per KM: " + (fare/100)/distance;
Round to some number of decimal points? This gives a HUGE float right now.

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        searchResult.replaceList( filteredRequests );
If I filter for a price per KM that is minimum 2, it returns a request with a price per KM of 1.951981... I assume that this is possibly a rounding error?

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        searchResult.replaceList( filteredRequests );
So I also tried this same case with a maximum of 2 (minimum of 0) and it didn't return that request (with a price per KM of 1.951981...)

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        searchResult.replaceList( filteredRequests );
There is a request with a price per KM of 1.04744539... This one works as expected if I use a maximum or minimum of 1. If I use a minimum of 1.05 (maximum of 2), this request is still returned. If I use a maximum of 1.05 (minimum of 0), the request is not returned. Again, possibly a rounding error somewhere? How precise do we want to be?

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +    public void performAsyncUpdate() {
Javadocs?

2016-11-21 07:49 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchActivity.java
> +    private void bundleFilters(Intent intent) {
I like this method a lot.

2016-11-21 07:49 UTC, sehoven commented on app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#7e57c2</color>
AHA! YOU ARE THE CULPRIT THAT GOT RID OF THE HOT PINK.

2016-11-21 15:08 UTC, MandyMeindersma commented on app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#7e57c2</color>
WE NEED HOT PINK!!!!
@kieter @Hreherch @MichaelParadis

2016-11-22 08:56 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchResultsActivity.java
I realize that this is kind of outside of the scope of your branch but could you do me a favour and add this **setTitle("Search Results");** under setContentView(...). There is a typo in the title in the main branch.

2016-11-22 08:57 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchResultsActivity.java
I'm sorry if this is hard to see from here. In the SearchResultsActivity.java file in the OnCreate method under the setContentView line.

2016-11-23 00:25 UTC, Hreherch commented on app/src/androidTest/java/comcmput301f16t01/github/carrier/ElasticUserControllerTest.java
>   */
@kieter

2016-11-23 01:04 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +    public void performAsyncUpdate() {
solved in another branch

2016-11-23 03:35 UTC, Hreherch commented
@sehoven Would love a quick look over :)

2016-11-23 05:56 UTC, sehoven commented
I put in 2 requests (user is shoven, keyword for both requests is periwinkle if you want to try to duplicate). I'm trying to filter by price. One has a price of $11.60, one has a price of $18.41. If I do a min of 0 and a max of 11.61, only the first is returned. Great. If I do a min of 11.61 with no max, no requests are returned (oh no!). If I do a min of 11.61 with a max of 20, the second request is returned (yay!). So something is up with the optional max perhaps.

2016-11-23 06:03 UTC, sehoven commented
For price by kilometer (using same examples as above), the first is 1.25, the second is 1.75. With any valid min and no max, no requests are returned. With a min of 1.22 and a max of 5, both requests are returned, bump min up to 1.23 and only the second is returned. With a min of 1.26 and a max of 1.67, I can still see the second request (the second request again has a value of 1.75), bump it down to 1.66 and it does what it's supposed to - I can't see the second request anymore.

2016-11-23 21:38 UTC, Hreherch commented
I left in float values when I converted to double, should be maybe okay now? @sehoven

2016-11-23 22:47 UTC, sehoven approved these changes

2016-11-23 22:48 UTC, merged