Search by address implemented
CMPUT301F16T01/Carrier pull request #167
Opened 2016-11-21 02:09 UTC by sehoven

2016-11-21 10:31 UTC, Hreherch requested changes
Looking good! 
Minor edits, mayhaps. 

One enhancement is that I rather be able to type in my search in the SearchAddressChoiceActivity. This way I can type in an address, hit go (this would be like a google search, where the results appear immediately below), and immediately see on the same activity the potential locations my address brought up.

2016-11-21 10:31 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> ->>>>>>> 92fda80c294f949b664f49d206e3dedeea1f17a7
I noticed you caught this here but I commented in your other pull request about it.

2016-11-21 10:31 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchAddressChoiceActivity.java
> +    // TODO http://stackoverflow.com/questions/32444863/google-gson-linkedtreemap-class-cast-to-myclass
Reminder for your TODO

2016-11-21 10:31 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchAddressChoiceActivity.java
> +public class SearchAddressChoiceActivity extends AppCompatActivity {
Needs top-level JavaDoc?

2016-11-21 10:31 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchActivity.java
> +    // TODO decide how to allow the user to enter the address
I believe you answered this TODO.

2016-11-21 16:13 UTC, sehoven commented
Just letting you know that I've seen your comments and I will address the major one first (search on same activity) sometime today.

2016-11-21 16:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Searching/SearchAddressChoiceActivity.java
> +public class SearchAddressChoiceActivity extends AppCompatActivity {
Like a javadoc on the activity class?

2016-11-22 05:11 UTC, Hreherch approved these changes

2016-11-22 05:12 UTC, merged