Offline view requests
CMPUT301F16T01/Carrier pull request #177
Opened 2016-11-23 03:31 UTC by kieter

This pull request covers US 08.02.01 #145 and US 08.01.01 #144 (View driver and rider requests while offline). 

To try this build then log in first while online, refresh by pulling down (or make a request) then close the app, go in airplane mode, and log in again.

2016-11-24 01:18 UTC, MandyMeindersma requested changes
I know this is tedious but could you go through each comment and add a 'done' once you have done it...

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/FareCalculator.java
> +     */
yaaassssss

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Toast.makeText(this, "Offline", Toast.LENGTH_SHORT).show();
can you change this toast to "You are offline."

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Toast.makeText(this, "Size of requestsWhereRider: " + Integer.toString(rc.getRiderInstance().size()), Toast.LENGTH_SHORT).show();
do we still need this?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/ElasticRequestController.java
> +            //TODO: ask bennett about this
did you ask bennnett? can you remove this todo? whats going on?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
>      // TODO rename this method? i.e. getRequestsWhereDriverOffered, or something
are you going to rename it? I do not think I care to what but you should get rid of the TODO

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            Log.i("Saving", "saveRiderRequests saved " + requestsWhereRider.size());
remove the log stuff

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            // For debugging
delete this commented out stuff please?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            Log.i("Saving", "saveRiderRequests saved " + requestsWhereRider.size());
and error catching stuff?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            out.flush();
delete debugging?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginActivity.java
> +        //TODO: if online, quicklogin, else, offlinelogin
why are these TODO's here?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginActivity.java
>          // TODO grab their username based on their ID?
why this TODO here? have you solved it? just make them log in manually?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginMemory.java
> +            e.printStackTrace();
what is e.printstackTrace?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginMemory.java
> +            e.printStackTrace();
gah thing kieter

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/UserController.java
> +    public boolean offlineLogInUser(String usernameToLogin, User cachedUser) {
Java docs? comments? anything?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginMemory.java
> +    public User loadUser() {
java docs comments? anything?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginMemory.java
> +    public void saveUser(User userToCache) {
java docs comment annything

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Users/LoginActivity.java
> +        if (ConnectionChecker.isThereInternet()) {
This is about line 37. could your java doc comments be more descriptive? more than one line if possible?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            e.printStackTrace();
ew. stack trace

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +     * For offline functionality. Loads the cached riderrequests.
change to "rider requests"

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
>      public RequestList fetchAllRequestsWhereRider( User rider ) {
java doc?

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
>      public RequestList fetchRequestsWhereRider(User rider, Integer... statuses ) {
java doc

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        if (!ConnectionChecker.isThereInternet()) {
java doc for this method

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Notifications/ConnectionChecker.java
> +                e.printStackTrace();
get rid of the stack thing

2016-11-24 01:18 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Notifications/ConnectionChecker.java
> +    //TODO: https://developer.android.com/reference/java/net/HttpURLConnection.html
did you tell sarah?

2016-11-24 19:18 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/Notifications/ConnectionChecker.java
> +    //TODO: https://developer.android.com/reference/java/net/HttpURLConnection.html
I told sarah

2016-11-24 19:21 UTC, kieter commented
DONE. I wrote some tests tooo @MandyMeindersma

2016-11-24 20:39 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
>      public RequestList fetchRequestsWhereRider(User rider, Integer... statuses ) {
It's in my branch.

2016-11-24 23:39 UTC, MandyMeindersma commented
lols more conflicts

2016-11-25 04:41 UTC, MandyMeindersma commented
@kieter am I safe to assume you have done everything I have commented?

2016-11-25 06:28 UTC, sehoven commented
I'm forcing this because Mandy was good with everything except for merge conflicts and we want to merge this branch before any others get merged first accidentally and force Kieter to fix more merge conflicts.

2016-11-25 06:28 UTC, merged