Rider confirm completion
CMPUT301F16T01/Carrier pull request #187
Opened 2016-11-24 01:45 UTC by MichaelParadis

Includes the confirmation of the driver as a rider for simplicity in testing.
Addresses #143 #142 #137 #136

2016-11-24 06:15 UTC, sehoven requested changes
Status does not update on MainActivity when the driver is confirmed (it should go to the filled in circle but it stays as the half-circle even though it shows up properly in the view request screen).

The flow seems to work pretty well, but I had to log in and out of accounts to test it. I wouldn't mind testing with someone else side-by-side tomorrow.

Overall I think your javadocs could be more descriptive. I highlighted the places I think this especially.

I'm not really sure where this is in the code, but the "Confirm Completion" button should be greyed out before I have chosen an offered driver (it doesn't let me press it, but I would like a visual cue). Also, after I press this button to complete, it should grey out again (since I can't press it anymore). It does it eventually if I leave the request and come back in, but it should do it automatically.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/OfferingDriversArrayAdapter.java
> + */
Auto-generated Javadoc. Please write a description of the class in the Javadoc.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/OfferingDriversArrayAdapter.java
> +     *
I would appreciate more description for what's going on here because there's a lot happening and I really had to dig into your code to understand.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/OfferingDriversArrayAdapter.java
> +                    adb.setMessage("Confirm Driver?");
Since we have the offering driver's username at this point, could we also put their username in the dialog box? To let the user know which driver it is they are confirming?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/DriverViewRequestActivity.java
> +     * @param v The view
The view? What is this? Which button is pressed to get here?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/DriverViewRequestActivity.java
> +     * @param view The current view.
Same thing with better description for the view

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +        }
Can you comment why you are doing this check?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +     * @param view The current view.
Same comment about view javadoc

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +            adb.setMessage("Can not complete request");
Better error message? Why can't we complete request?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>          // TODO why does it say "sarah" even though there is no confirmedDriver?
I believe this TODO has been solved?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +            Toast.makeText(RiderRequestActivity.this, "Here", Toast.LENGTH_SHORT).show();
What is this Toast even doing? Delete?

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>              String startPoint = request.getStart().getLatLong();
This can be simplified to just **startAddressTextView.setText(request.getStart().toString());** You can replace lines 294 to 298 (the whole conditional) with this one line.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>              String endPoint = request.getEnd().getLatLong();
Same simplification as above. (I know you didn't write these but I just know that it can be fixed here).

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +        } else {
Could we just grey out the cancel button when the request is completed? It is an action that is no longer allowed at that point so for consistency I think that would be best.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/activity_rider_view_request.xml
> +
Please move this back. Fare amount should be at the top. I don't know why this was changed.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/activity_rider_view_request.xml
>              android:textAllCaps="false"
The other button is all caps so it's weird that this one is not? Also I think the string is too long. I think COMPLETE would suffice.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/offeringdriverslist_item.xml
> +        android:clickable="false" />
This button is not wide enough. It cuts off the text. Also the button style should be the same as the rest of the app (copy from any other XML with a button).

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/offeringdriverslist_item.xml
> +        android:background="@android:drawable/screen_background_light_transparent" />
Tbh I really hate this eye and I think we should delete it everywhere. Maybe a group discussion though...

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/offeringdriverslist_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think this whole item feels weird aesthetically in general. Maybe we just need to make the text bigger or something to fill up the empty space but it just looks awkward to me.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/res/layout/rider_view_offering_drivers.xml
> +    android:paddingTop="@dimen/activity_vertical_margin"
I don't know what value we are using for padding elsewhere but this feels bigger than the others and I would like it smaller to be more cohesive.

2016-11-24 06:15 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +            Toast.makeText(activity, "PAY FOR REQUEST", Toast.LENGTH_SHORT).show();
Delete this toast please.

2016-11-24 20:12 UTC, MichaelParadis commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +            adb.setMessage("Can not complete request");
Removed this dialog since the button will not be clickable unless you can complete a request.

2016-11-24 20:51 UTC, MichaelParadis commented
@sehoven I have addressed your feedback

2016-11-25 04:12 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>          // TODO why does it say "sarah" even though there is no confirmedDriver?
Delete this TODO.

2016-11-25 04:12 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>              String startPoint = request.getStart().getLatLong();
Make this change please. (I know you didn't write these lines but it can be fixed simplified here).

2016-11-25 04:13 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
>              String endPoint = request.getEnd().getLatLong();
Make this change please. (I know you didn't write these lines but it can be fixed simplified here).

2016-11-25 04:34 UTC, sehoven commented
When I cancel a request, I can see that the status changes and the Cancel button is greyed out before it sends me back to the MainActivity, as I expect. When I click back into the request though, I can click on the Cancel button again and an error dialogue pops up. When the status on a request is "cancelled" I would like both buttons at the bottom of the screen to be greyed out. Don't let me press it still.

2016-11-25 05:03 UTC, sehoven commented
Fix the above issue and the merge conflicts and then I am happy with it.

2016-11-25 05:13 UTC, sehoven approved these changes

2016-11-25 05:14 UTC, merged