Fixes the issue 193
CMPUT301F16T01/Carrier pull request #194
Opened 2016-11-25 05:46 UTC by MichaelParadis

Quick fix for #193 which allowed the rider to go to the confirmation of driver screen after they have already confirmed the driver.

2016-11-25 08:08 UTC, Hreherch requested changes
Try passing null and report back. 
The code will be easier to read if you explain what it does in the comments.

2016-11-25 08:08 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RiderRequestActivity.java
> +        driverTextView.setOnClickListener(new View.OnClickListener() {
I think you could just pass null? Please test and report back (I'm not sure).

2016-11-25 22:46 UTC, MichaelParadis commented
@Hreherch Set it to null and it still works.

2016-11-26 23:39 UTC, Hreherch approved these changes

2016-11-26 23:39 UTC, merged