Accepting user cases
CMPUT301F16T01/Carrier pull request #20
Opened 2016-10-11 22:01 UTC by MichaelParadis

Provides the testing for accepting user cases. This closes issue #6.

2016-10-11 22:34 UTC, Hreherch commented
We think I wrote it wrong in the GitHub Issues, so Sarah will be checking this over now. I am as well, but I will not submit a review.

2016-10-12 00:38 UTC, Hreherch commented
driverPendingAccepts:
"Get open request is not return any open requests" spelling/grammar could be enhanced for clarity when this test fails (This same message is in driverAccept)
Further clarity could be provided in other messages, you use getOpenRequests but you don't specify that the implementation of getOpenRequests hasn't returned a request that it should have.
We can use the request to see the drivers, and shouldn't have to use the controller (The view can see the model)


driverAcceptedRequests:
We can pull the model directly, instead of using the controller to getConfirmedDriver? (i.e. view can see model, but cannot edit it)

notifyDriver:
good!

2016-10-12 00:54 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/Driver.java
> -
i want this back

2016-10-12 01:59 UTC, sehoven requested changes
Please fix the formatting to remove blank lines where necessary.

Some points in the user cases are not addressed. Please address these or give a reason why they are not a concern for the unit tests.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +        assertTrue("The request has not been marked as accepted by the driver.", rc.getPendingRequests(driver).size() == 1);
This is confusing to me. We are talking about requests and their status from two different perspectives: the rider and the driver. Based on the function name alone this is not clear to me which one we are talking about so the two tests were ambiguous. Also, "pending" is not a word that is well-defined within our application. This needs to be addressed in the Glossary.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Please delete lines 28-31.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +     * (US 05.01.01) As a driver, I want to accept a request I agree with and accept that offered payment upon completion.
The user case specifies "accept that offered payment upon completion". This is not addressed anywhere in the test.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +     * (US 05.01.01) As a driver, I want to accept a request I agree with and accept that offered payment upon completion.
We could also just need to define more clearly when the offered payment is accepted and the request completed.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Please delete line 56.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Please delete line 73.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Please delete lines 88-89.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +     * (US 05.02.01) As a driver, I want to view a list of things I have accepted that are pending, each request with its description, and locations.
It is never addressed that "each request with its description, and locations".

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +        assertFalse("The request is still available to be accepted by other drivers", rc.getAvailableRequests().contains(request));
I kind of understand what "Available Request" does for us but how is this represented in the Request class? I think we need to define this better. I feel like it is too ambiguous.

2016-10-12 01:59 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +        rc.addDriver(request, driver);
Could we add a test under line 68 to confirm that it IS available to other drivers? (inverse of line 71) Or is this outside the scope of this test case?

2016-10-13 00:34 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +        assertTrue("The request has not been marked as accepted by the driver.", rc.getPendingRequests(driver).size() == 1);
Should be addressed.

2016-10-13 00:34 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Done

2016-10-13 00:38 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +     * (US 05.02.01) As a driver, I want to view a list of things I have accepted that are pending, each request with its description, and locations.
Done

2016-10-13 00:38 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Done

2016-10-13 00:46 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Done

2016-10-13 00:46 UTC, MichaelParadis commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +
Done

2016-10-13 01:18 UTC, sehoven commented on app/src/test/java/comcmput301f16t01/github/carrier/AcceptingTests.java
> +        assertFalse("The request is still available to be accepted by other drivers", rc.getAvailableRequests().contains(request));
This has been addressed in the glossary.

2016-10-13 01:18 UTC, sehoven approved these changes

2016-10-13 01:18 UTC, merged