Offline make request
CMPUT301F16T01/Carrier pull request #201
Opened 2016-11-26 18:26 UTC by kieter

You can now make rider requests while offline and have them be added to elastic search once connectivity comes back. Covers #146 

An example test:
Log in online, go offline, make a request, go back online, swipe down to refresh.

2016-11-27 03:23 UTC, sehoven requested changes
If I make 2 requests while offline, then I go back online and refresh, only one request shows up. If I refresh again, both show up (as I expect).

Try putting it in onPostExecute

2016-11-27 03:23 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +    private static final String OFFLINE_FILENAME = "OfflineRequests.sav";
Could you call this OFFLINE_REQUEST_FILENAME or something more descriptive to show that it is dealing with the requests specifically?

2016-11-27 03:23 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            if (!internetConnection) {
Maybe just make this an if-else?

2016-11-27 03:23 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +                Toast.makeText(saveContext, "Offline saving" + Integer.toString(offlineRiderRequests.size()), Toast.LENGTH_SHORT).show();
Delete this Toast.

2016-11-27 10:26 UTC, sehoven commented
I was trying to run a branch that was branched off of your branch to work on a different issue and it won't let me do anything on the app. It crashes every time I try to do pretty much anything (and I'm not sure when this started happening) .

<img width="1165" alt="screen shot 2016-11-27 at 3 24 46 am" src="https://cloud.githubusercontent.com/assets/17459185/20647422/14ae2976-b451-11e6-9072-61795948a8f8.png">

2016-11-27 21:42 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +    private static final String OFFLINE_FILENAME = "OfflineRequests.sav";
Did itttt

2016-11-28 01:16 UTC, sehoven commented on app/src/main/java/comcmput301f16t01/github/carrier/Requests/RequestController.java
> +            List<Address> addresses = geocoder.getFromLocation(latitude, longitude, 1);
Import List type (from me merging my branch)

2016-11-28 04:35 UTC, sehoven approved these changes

2016-11-28 04:35 UTC, merged