Show request status
CMPUT301F16T01/Carrier pull request #72
Opened 2016-11-01 00:20 UTC by MandyMeindersma

2016-11-01 00:21 UTC, MandyMeindersma commented
@kieter  please review

2016-11-02 05:18 UTC, kieter commented
So before I start I noticed that not all of the commits on this pull request are yours. I will start with your commits on this pull request @MandyMeindersma (commits 7a77de, befb82e, 6c60a11) viewing them independently of all of Bennett's commits.

2016-11-02 05:33 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/driverViewRequestActivity.java
> +public class DriverViewRequestActivity extends AppCompatActivity {
I'm not entirely sure what this class is for, I think it may have been an accident? It's name isn't following CamelCase and it causes an error when trying to build the app. I just commented it out when trying to build. Your choice what to do with it.

2016-11-02 05:43 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Intent intent = new Intent(this, HelpActivity.class);
I tested this on my phone. The app crashes when you hit the "Help" option in the menu. Try getActivity() instead of this as the first argument.

2016-11-02 05:49 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/HelpActivity.java
> +public class HelpActivity extends AppCompatActivity {
I do in general like the way HelpActivity looks. It seems a little bit empty, try spreading out the spacing between the icons in the legend, that might help. This screen is a little harsh on the eyes with all the white but we'll talk about colour/icons later.

2016-11-02 05:52 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +                    intent.putExtras(bundle);
Excellent! These bundle things are cool 📦

2016-11-02 05:53 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            /*requestListView.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
I'm just curious why this is commented out haha.

2016-11-02 05:54 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/RequestAdapter.java
> +                        //statusImageView.setBackgroundResource(R.color.openStatus);
There's a lot of commented out lines, which is totally fine. I probably do this lots. It just kinda makes the code a bit messy.

2016-11-02 05:57 UTC, kieter commented on app/src/main/res/layout/activity_rider_view_request.xml
> +            android:id="@+id/imageView_requestStatus"
I don't know if this is caused by your code but the status icon for every request is kind of super pushed into the side and difficult to see.

2016-11-02 05:59 UTC, kieter commented on app/src/main/res/values/strings.xml
> +    <string name="padding">10dp</string>
Good job remembering to put this stuff in strings.xml! I'm totally forgetting to do this 💁

2016-11-02 06:02 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/RiderRequestActivity.java
> +            switch (request.getStatus()) {
I like this switch. It's nice. I'm trying to use switches more often 👍 .

2016-11-02 06:11 UTC, kieter commented on app/src/main/res/layout/activity_help_legend.xml
> +<?xml version="1.0" encoding="utf-8"?>
I do in general like the way HelpActivity looks. It seems a little bit empty, try spreading out the spacing between the icons in the legend, that might help. This screen is a little harsh on the eyes with all the white but we'll talk about colour/icons later.

2016-11-02 06:12 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/Request.java
> +        // TODO make an actual test for this (Mandy)
There is no test for this. A super simple one would be fine 😄

2016-11-02 06:20 UTC, kieter requested changes
I'm just summarizing my comments in the files, for context, go see those. The app currently crashes when you select the help option in the menu, try the fix I mention in my comments. There's a weird class called driverViewRequestActivity.java which currently causes an error and this activity does nothing yet. The list objects seem to push the status icons beyond a viewable threshold, but otherwise excellent choice of icons, I think they are very telling. I like the way the xmls look. There's plenty of commented out code, which is fine, just clean up some of it. Do some JavaDocs to save everyone some documentation later, plus you currently know really well what the stuff you just made is doing, perfect time for docs 👍  Generally I think your code is clever, high quality and seems well tested and only has some small bugs. Very good job on this one Mandy! Only some small changes are required :octocat: .

2016-11-02 06:23 UTC, kieter commented
Once you've made changes, ask me to look over this again and I'll merge it 😃

2016-11-02 06:28 UTC, kieter commented
Sorry, final thought. There's a few merge requests in this one, pls fix.

2016-11-02 07:17 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Intent intent = new Intent(this, HelpActivity.class);
Normally `MainActivity.this` works

2016-11-02 15:42 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            /*requestListView.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
This was something Bennett wanted to do originally but I think we agreed to not do it. I didn't want to delete the code fully.

2016-11-02 15:42 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/RequestAdapter.java
> +                        //statusImageView.setBackgroundResource(R.color.openStatus);
This was something Bennett wanted to do originally but I think we agreed to not do it. I didn't want to delete the code fully.

2016-11-02 15:42 UTC, MandyMeindersma commented on app/src/main/res/layout/activity_rider_view_request.xml
> +            android:id="@+id/imageView_requestStatus"
Which side? when you view the list of requests right?

2016-11-02 15:44 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/Request.java
> +        // TODO make an actual test for this (Mandy)
Most of our tests need revision... :P I may slowly work on all request tests next week...

2016-11-02 15:48 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/driverViewRequestActivity.java
> +public class DriverViewRequestActivity extends AppCompatActivity {
![image](https://cloud.githubusercontent.com/assets/17459171/19935918/6ac52c34-a0e1-11e6-9075-439987bdeadd.png)

I named it to be like the rest... how did it run when you commented it out?!? I refactored the code with that name change...

2016-11-02 15:49 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Intent intent = new Intent(this, HelpActivity.class);
fixed to MainActivity.this

2016-11-02 15:51 UTC, kieter commented on app/src/main/java/comcmput301f16t01/github/carrier/driverViewRequestActivity.java
> +public class DriverViewRequestActivity extends AppCompatActivity {
Idk haha. I got an error from there on build and just commented it out to run and it worked. I could be crazy.

2016-11-02 15:53 UTC, kieter commented on app/src/main/res/layout/activity_rider_view_request.xml
> +            android:id="@+id/imageView_requestStatus"
Yaa. Don't know if it's just because the other stuff in the list adapter is taking up too much space or what.

2016-11-02 15:53 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/driverViewRequestActivity.java
> +public class DriverViewRequestActivity extends AppCompatActivity {
Interesting... My emulator runs....

2016-11-02 15:56 UTC, MandyMeindersma commented on app/src/main/res/layout/activity_help_legend.xml
> +<?xml version="1.0" encoding="utf-8"?>
I spaced it out a little more. If we do not like it we can change it. I USED A STRING FOR THE PADDING BETWEEN THEM SO IT IS EASY TO CHANGE!!

2016-11-02 16:34 UTC, MandyMeindersma commented on app/src/main/java/comcmput301f16t01/github/carrier/MainActivity.java
> +            Intent intent = new Intent(this, HelpActivity.class);
gah. Its not working... I will have to work on this at the airport... ugh... this may be late ish

2016-11-02 23:28 UTC, MandyMeindersma commented on app/src/main/res/layout/activity_help_legend.xml
> +<?xml version="1.0" encoding="utf-8"?>
HAHAHAHAHHA HILARIOUS JUST KIDDING. MY SAVING OF STRING IS WHAT MADE HELP LEGEND CRASH HAHAHAHAHAHAHAHAHAHAHA

2016-11-04 18:15 UTC, merged