Merge Login Memory Feature
CMPUT301F16T01/Carrier pull request #74
Opened 2016-11-01 05:30 UTC by Hreherch

A small feature that sets the app to remember what you logged in last as.
Tested on phone. 

(Also contains my work for this week, Request-Adapter, so review away!)

2016-11-01 22:32 UTC, MichaelParadis requested changes
Looks good, only a few small changes.

2016-11-01 22:32 UTC, MichaelParadis commented on app/src/main/java/comcmput301f16t01/github/carrier/RequestAdapter.java
> +                String startLoc = "To: " + request.getStart().toString();
Should be "From:" instead of "To"

2016-11-01 22:32 UTC, MichaelParadis commented on app/src/main/java/comcmput301f16t01/github/carrier/RequestAdapter.java
> +                String price = "$" + Float.toString(request.getFare() / 100);
Could use the locale to get the currency used instead of assuming it is in $.

2016-11-01 22:32 UTC, MichaelParadis commented on app/src/main/res/layout/activity_new_user.xml
> +        android:hint="e.g. 0118-999-881-999-119-725... 3"
Love the IT Crowd reference.

2016-11-02 01:56 UTC, Hreherch commented
Should be okay. 
Maybe merge this one before the others since it contains work that the other branches started from?

2016-11-02 20:54 UTC, MichaelParadis approved these changes

2016-11-02 22:20 UTC, merged