Clickable username
CMPUT301F16T01/Carrier pull request #88
Opened 2016-11-06 19:11 UTC by kieter

Sad. There's conflicts. I'll fix them after a review.

2016-11-06 19:26 UTC, kieter commented
Btw, once this pull request is accepted. Please use my TextView (called UsernameTextView) for any usernames.

2016-11-06 19:40 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/UserProfileActivity.java
> +
Make sure this doesn't break viewing a profile normally (i.e. through the MainActivity "view profile" button).

2016-11-06 19:41 UTC, Hreherch commented on app/src/main/java/comcmput301f16t01/github/carrier/UserProfileActivity.java
> +
We should also consider if we want to always pull from elastic search when we do this activity. To get the most up to date information (but blocks the user from getting information while they are offline)

2016-11-06 19:52 UTC, Hreherch requested changes
java.lang.IllegalStateException: Could not find method onClickDriverUsernameTextView(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.widget.LinearLayout

2016-11-10 01:49 UTC, Hreherch approved these changes

2016-11-10 01:50 UTC, merged